### ISSUE TITLE
cr-like-em causes thread panick (Alpha Sum too small) w/ high duplicates

### ISSUE THREAD

**Issue by bugneville** [COMBINE-lab/alevin-fry#25]
**summary:**
_cr-like-em_ appears to hang _alevin-fry quant_ if the FASTQ being processed has high duplicates (~>71%?) e.g.,:

**data:**
https://www.10xgenomics.com/resources/datasets/4-k-pbm-cs-from-a-healthy-donor-2-standard-2-1-0

**cmd:**
```
singularity exec --cleanenv --bind $PWD:/workdir --pwd /usefulaf/bash usefulaf_latest.sif ./simpleaf quant \
-1 /data/pbmc4k_S1_L001_R1_001.fastq.gz -2 /data/pbmc4k_S1_L001_R2_001.fastq.gz \
-i /workdir/human_CR_3.0_splici/index \
-m /workdir/human_CR_3.0_splici/ref/transcriptome_splici_fl93_t2g_3col.tsv \
-o /workdir/quants/test \
-f u -c v2 -r cr-like-em -t 16
```

**error:**
```
thread '<unnamed>' panicked at 'Alpha Sum too small', libradicl/src/em.rs:218:5
stack backtrace:
   0:     0x55d630004cc2 - std::backtrace_rs::backtrace::libunwind::trace::ha5edb8ba5c6b7a6c
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55d630004cc2 - std::backtrace_rs::backtrace::trace_unsynchronized::h0de86d320a827db2
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55d630004cc2 - std::sys_common::backtrace::_print_fmt::h97b9ad6f0a1380ff
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55d630004cc2 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h14be7eb08f97fe80
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55d62feb321f - core::fmt::write::h2ca8877d3e0e52de
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/fmt/mod.rs:1094:17
   5:     0x55d6300028e5 - std::io::Write::write_fmt::h64f5987220b618f4
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/io/mod.rs:1584:15
   6:     0x55d6300068fb - std::sys_common::backtrace::_print::h7f1a4097308f2e0a
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55d6300068fb - std::sys_common::backtrace::print::h1f799fc2ca7f5035
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55d6300068fb - std::panicking::default_hook::{{closure}}::hf38436e8a3ce1071
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:208:50
   9:     0x55d63000717f - std::panicking::default_hook::he2f8f3fae11ed1dd
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:225:9
  10:     0x55d63000717f - std::panicking::rust_panic_with_hook::h79a18548bd90c7d4
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:591:17
  11:     0x55d62feec754 - std::panicking::begin_panic::{{closure}}::hd1fbb432e5b7fa61
  12:     0x55d62fee95dc - std::sys_common::backtrace::__rust_end_short_backtrace::h73000f4d2864a3cf
  13:     0x55d62fe21f6a - std::panicking::begin_panic::h89d0de012afc9e31
  14:     0x55d62ff29cb7 - libradicl::em::em_optimize_subset::h8d61b85ad05da835
  15:     0x55d62fef6849 - libradicl::quant::do_quantify::{{closure}}::h16178b4066ec1cd8
  16:     0x55d62fee9c14 - std::sys_common::backtrace::__rust_begin_short_backtrace::h6f9c3711ffe16ea1
  17:     0x55d62feecbbc - core::ops::function::FnOnce::call_once{{vtable.shim}}::h15826baaec173458
  18:     0x55d63000a79a - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h75c2ca1daad47228
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/alloc/src/boxed.rs:1546:9
  19:     0x55d63000a79a - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hdf9f8afc9d34e311
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/alloc/src/boxed.rs:1546:9
  20:     0x55d63000a79a - std::sys::unix::thread::Thread::new::thread_start::hc238bac7748b195d
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys/unix/thread.rs:71:17
  21:     0x7fba13604609 - start_thread
  22:     0x7fba133d6293 - clone

```
**work around:**
reducing duplicates (e.g., splitting FASTQ) allows the command to run to completion.

**Comment by rob-p** [comment]
Thanks so much for the detailed bug report!  We’ll look into this and report back.  I’ll also cc @DongzeHE and @mohsenzakeri to help look into it.

**Comment by bugneville** [comment]
np -- thanks for the great tools.  just a bit more info -- _cr-like_ ran on all FASTQs tested, but ~ half dozen FASTQ pairs that had high duplicates (as reported by FastQC) all panicked with _cr-like-em_.  correlation != causation, but is my best guess.

**Comment by rob-p** [comment]
Hi @bugneville,

  I'm looking into this now and working on tracking down the root cause.  One thing that occurs to me is that this message (and the corresponding panic) should only happen when the alpha sum is too small *for the entire cell*.  This means that there are cells where _all_ of the reads are highly multi-mapping at the gene level, and the genes to which they map are all being filtered (total abundance after EM convergence < 0.01).  I'm *guessing* this is only happening in cells with a very small number of total reads anyway.

  To check this, could you see on your end if you get this error if you apply the `knee` filtering rather than processing the unfiltered permit-list?  To be clear, we still intend to fix the behavior on all code paths, but I just want to make sure that this presumptive cause is, in fact, what is leading to the error.

**Comment by bugneville** [comment]
the cause you outlined makes sense -- and what you suggested (_-k_(_neeing_) the counts) avoids the 'Alpha Sum too small' thread panick on all the "high dup" files I previously had issues with when unfiltered.  definitely (hopefully) an edge use case, but what you recommend moving forward sounds good.  thanks for the quick diagnosis!
